version: '3'

services:
  web:
    build: ./python
    ports:
      - "2600:2600"
    container_name: django
    volumes:
      - ./python:/code
    depends_on:
      - db
    networks: 
      - dj_net

  db:
    build: ./db
    restart: always
    container_name: data
    # env_file:
    #   - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks: 
      - dj_net

volumes:
  mariadb_data:

networks:
  dj_net:
    driver: bridge
