version: '3'

services:
  web:
    build: ./python
    ports:
      - "8000:8000"
    volumes:
      - python:/code
    depends_on:
      - db
    networks: 
      - dj_net

  db:
    build: ./db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks: 
      - dj_net

volumes:
  mariadb_data:
  python:

networks:
  dj_net:
    driver: bridge
